application: blok-hrd
version: 5
runtime: python27
api_version: 1
threadsafe: false

handlers:

- url: /templates
  static_dir: templates

- url: /static
  static_dir: static

- url: /block
  static_dir: block

- url: .*
  script: main.py


